import os
import sqlite3
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from mcp.server.fastmcp import FastMCP

DB_PATH = os.environ.get("BPJS_SQLITE_DB", "")
OUTPUT_DIR = os.environ.get("BPJS_PDF_OUTPUT_DIR", "./output/pdf")
LOG_FILE = os.path.join(os.path.dirname(__file__), "mcp_pdf.log")
LOGO_PATH = os.environ.get("BPJS_PDF_LOGO", "./assets/bpjs_logo.png")

mcp = FastMCP("bpjs-pdf-summary")


def log(msg: str) -> None:
    with open(LOG_FILE, "a", encoding="utf-8") as f:
        f.write(f"[{datetime.now().isoformat()}] {msg}\n")


def get_conn():
    if not DB_PATH:
        raise ValueError("BPJS_SQLITE_DB is not set.")
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def ensure_output_dir():
    os.makedirs(OUTPUT_DIR, exist_ok=True)


def format_currency(value) -> str:
    try:
        amount = int(round(float(value)))
        return f"Rp {amount:,}".replace(",", ".")
    except Exception:
        return f"Rp {value}"


def draw_wrapped_text(
    c,
    text,
    x,
    y,
    max_width,
    line_height=13,
    font_name="Helvetica",
    font_size=10,
):
    c.setFont(font_name, font_size)
    words = str(text).split()
    line = ""
    current_y = y

    for word in words:
        test_line = f"{line} {word}".strip()
        if c.stringWidth(test_line, font_name, font_size) <= max_width:
            line = test_line
        else:
            c.drawString(x, current_y, line)
            current_y -= line_height
            line = word

    if line:
        c.drawString(x, current_y, line)
        current_y -= line_height

    return current_y


def draw_label_value(c, label, value, x, y, label_width=4.2 * cm, font_size=10):
    c.setFont("Helvetica-Bold", font_size)
    c.drawString(x, y, f"{label}")
    c.setFont("Helvetica", font_size)
    c.drawString(x + label_width, y, f": {value}")
    return y - 14


def draw_bullet_list(c, items, x, y, max_width, bullet="-", line_height=13, font_size=10):
    current_y = y
    for item in items:
        current_y = draw_wrapped_text(
            c,
            f"{bullet} {item}",
            x,
            current_y,
            max_width,
            line_height=line_height,
            font_size=font_size,
        )
    return current_y


def draw_section_box(c, title, x, y, width, header_height=18):
    c.setStrokeColor(colors.HexColor("#D7E3F4"))
    c.setFillColor(colors.HexColor("#F6FAFF"))
    c.roundRect(x, y - header_height, width, header_height, 6, stroke=1, fill=1)

    c.setFillColor(colors.HexColor("#1F3A5F"))
    c.setFont("Helvetica-Bold", 11)
    c.drawString(x + 8, y - 12, title)

    return y - header_height - 10


def draw_header(c, title, subtitle="", case_id=None):
    width, height = A4
    left_margin = 2 * cm
    top_y = height - 1.6 * cm

    # Logo area
    logo_width = 2.3 * cm
    logo_height = 2.3 * cm

    if os.path.exists(LOGO_PATH):
        try:
            logo = ImageReader(LOGO_PATH)
            c.drawImage(
                logo,
                left_margin,
                top_y - logo_height + 4,
                width=logo_width,
                height=logo_height,
                preserveAspectRatio=True,
                mask="auto",
            )
        except Exception as e:
            log(f"Logo load failed: {e}")

    text_x = left_margin + 2.9 * cm

    c.setFillColor(colors.HexColor("#0E2F5A"))
    c.setFont("Helvetica-Bold", 16)
    c.drawString(text_x, top_y, "BPJS Claims Assistance")

    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 15)
    c.drawString(text_x, top_y - 18, title)

    c.setFont("Helvetica", 9)
    c.setFillColor(colors.HexColor("#555555"))
    if subtitle:
        c.drawString(text_x, top_y - 32, subtitle)

    meta_y = top_y - 46
    c.setFont("Helvetica", 8.5)
    c.setFillColor(colors.HexColor("#666666"))
    c.drawString(text_x, meta_y, f"Tanggal pembuatan: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    if case_id:
        c.drawString(text_x + 8.5 * cm, meta_y, f"Case ID: {case_id}")

    line_y = top_y - 56
    c.setStrokeColor(colors.HexColor("#2E75B6"))
    c.setLineWidth(1.2)
    c.line(left_margin, line_y, width - 2 * cm, line_y)

    return line_y - 16


def draw_footer(c):
    width, _ = A4
    footer_y = 1.1 * cm

    c.setStrokeColor(colors.HexColor("#D9D9D9"))
    c.setLineWidth(0.6)
    c.line(2 * cm, footer_y + 10, width - 2 * cm, footer_y + 10)

    c.setFont("Helvetica-Oblique", 8)
    c.setFillColor(colors.HexColor("#666666"))
    c.drawString(2 * cm, footer_y, "Generated by BPJS Claims Assistance")
    c.drawRightString(width - 2 * cm, footer_y, "Dokumen internal untuk kebutuhan review operasional")


def new_page_if_needed(c, y, threshold=3.2 * cm):
    if y < threshold:
        draw_footer(c)
        c.showPage()
        new_y = draw_header(c, "Lanjutan Dokumen", "Continued")
        return new_y
    return y


@mcp.tool()
def create_case_summary_pdf(case_id: str) -> str:
    """Create a PDF summary for one claim case based on current operational data."""
    log(f"Tool called: create_case_summary_pdf case_id={case_id}")
    ensure_output_dir()

    with get_conn() as conn:
        case_row = conn.execute(
            """
            SELECT case_id, participant_id, participant_name, region, provider_type,
                   facility_name, claim_type, diagnosis_group, claim_amount, status,
                   priority_level, anomaly_score, suspected_issue, owner_unit
            FROM claim_cases
            WHERE case_id = ?
            """,
            (case_id,),
        ).fetchone()

        review_row = conn.execute(
            """
            SELECT case_id, queue_status, assigned_reviewer, assigned_team,
                   sla_due_date, overdue_days, next_action, escalation_level
            FROM review_queue
            WHERE case_id = ?
            """,
            (case_id,),
        ).fetchone()

    if not case_row:
        return f"Kasus {case_id} tidak ditemukan."

    filename = f"case_summary_{case_id}.pdf"
    file_path = os.path.join(OUTPUT_DIR, filename)

    c = canvas.Canvas(file_path, pagesize=A4)
    width, _ = A4
    x = 2 * cm
    content_width = width - 4 * cm

    y = draw_header(
        c,
        "Ringkasan Kasus Klaim",
        "Dokumen ringkas untuk kebutuhan review kasus",
        case_id=case_id,
    )

    y = draw_section_box(c, "Identitas Kasus", x, y, content_width)
    fields = [
        ("Case ID", case_row["case_id"]),
        ("Participant ID", case_row["participant_id"]),
        ("Nama Peserta", case_row["participant_name"]),
        ("Region", case_row["region"]),
        ("Jenis Provider", case_row["provider_type"]),
        ("Fasilitas", case_row["facility_name"]),
        ("Tipe Klaim", case_row["claim_type"]),
        ("Diagnosis Group", case_row["diagnosis_group"]),
        ("Nilai Klaim", format_currency(case_row["claim_amount"])),
        ("Status Klaim", case_row["status"]),
        ("Priority Level", case_row["priority_level"]),
        ("Anomaly Score", case_row["anomaly_score"]),
        ("Suspected Issue", case_row["suspected_issue"]),
        ("Owner Unit", case_row["owner_unit"]),
    ]

    for label, value in fields:
        y = new_page_if_needed(c, y)
        y = draw_label_value(c, label, value, x + 0.2 * cm, y)

    y -= 8
    y = new_page_if_needed(c, y)
    y = draw_section_box(c, "Status Review", x, y, content_width)

    if review_row:
        review_fields = [
            ("Queue Status", review_row["queue_status"]),
            ("Assigned Reviewer", review_row["assigned_reviewer"]),
            ("Assigned Team", review_row["assigned_team"]),
            ("SLA Due Date", review_row["sla_due_date"]),
            ("Overdue Days", review_row["overdue_days"]),
            ("Next Action", review_row["next_action"]),
            ("Escalation Level", review_row["escalation_level"]),
        ]
        for label, value in review_fields:
            y = new_page_if_needed(c, y)
            y = draw_label_value(c, label, value, x + 0.2 * cm, y)
    else:
        y = draw_wrapped_text(
            c,
            "Tidak ada data review queue untuk kasus ini.",
            x + 0.2 * cm,
            y,
            content_width - 0.4 * cm,
        )

    y -= 8
    y = new_page_if_needed(c, y)
    y = draw_section_box(c, "Ringkasan Singkat", x, y, content_width)

    summary_lines = [
        f"Kasus {case_row['case_id']} berada pada status {case_row['status']} dengan nilai klaim {format_currency(case_row['claim_amount'])}.",
        f"Kasus terkait peserta {case_row['participant_name']} di region {case_row['region']} dan fasilitas {case_row['facility_name']}.",
        f"Indikasi utama yang tercatat adalah: {case_row['suspected_issue']}.",
    ]

    if review_row:
        summary_lines.append(
            f"Kasus saat ini ditangani oleh {review_row['assigned_reviewer']} dengan next action: {review_row['next_action']}."
        )

    y = draw_bullet_list(c, summary_lines, x + 0.2 * cm, y, content_width - 0.4 * cm)

    y -= 8
    y = new_page_if_needed(c, y)
    y = draw_section_box(c, "Recommended Next Action", x, y, content_width)

    recommended_actions = []
    if review_row:
        if review_row["overdue_days"] and int(review_row["overdue_days"]) > 7:
            recommended_actions.append("Prioritaskan review karena kasus telah melewati ambang overdue operasional.")
        if review_row["queue_status"] == "Escalated":
            recommended_actions.append("Lakukan koordinasi dengan supervisor untuk validasi tindak lanjut eskalasi.")
        if review_row["next_action"]:
            recommended_actions.append(f"Tindak lanjut saat ini: {review_row['next_action']}.")

    if not recommended_actions:
        recommended_actions.append("Lanjutkan review sesuai status dan panduan operasional yang berlaku.")

    y = draw_bullet_list(c, recommended_actions, x + 0.2 * cm, y, content_width - 0.4 * cm)

    draw_footer(c)
    c.save()

    return (
        f"PDF berhasil dibuat.\n"
        f"Nama file: {filename}\n"
        f"Lokasi file: {file_path}"
    )


@mcp.tool()
def create_operational_summary_pdf() -> str:
    """Create a PDF operational summary for supervisors based on current claim review data."""
    log("Tool called: create_operational_summary_pdf")
    ensure_output_dir()

    with get_conn() as conn:
        status_rows = conn.execute(
            """
            SELECT status, COUNT(*) AS total_cases
            FROM claim_cases
            GROUP BY status
            ORDER BY total_cases DESC
            """
        ).fetchall()

        overdue_rows = conn.execute(
            """
            SELECT case_id, queue_status, assigned_reviewer, overdue_days, next_action
            FROM review_queue
            WHERE overdue_days > 3
            ORDER BY overdue_days DESC
            LIMIT 10
            """
        ).fetchall()

        reviewer_rows = conn.execute(
            """
            SELECT assigned_reviewer, COUNT(*) AS total_cases
            FROM review_queue
            GROUP BY assigned_reviewer
            ORDER BY total_cases DESC
            LIMIT 10
            """
        ).fetchall()

        high_risk_rows = conn.execute(
            """
            SELECT c.case_id, c.participant_name, c.anomaly_score, r.overdue_days
            FROM claim_cases c
            JOIN review_queue r ON c.case_id = r.case_id
            WHERE r.overdue_days > 7
              AND c.status IN ('Dalam Review', 'Eskalasi')
            ORDER BY c.anomaly_score DESC, r.overdue_days DESC
            LIMIT 5
            """
        ).fetchall()

    filename = f"operational_summary_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    file_path = os.path.join(OUTPUT_DIR, filename)

    c = canvas.Canvas(file_path, pagesize=A4)
    width, _ = A4
    x = 2 * cm
    content_width = width - 4 * cm

    y = draw_header(
        c,
        "Ringkasan Operasional Klaim",
        "Dokumen brief operasional untuk supervisor",
    )

    y = draw_section_box(c, "Jumlah Kasus per Status", x, y, content_width)
    items = [f"{row['status']}: {row['total_cases']} kasus" for row in status_rows]
    y = draw_bullet_list(c, items, x + 0.2 * cm, y, content_width - 0.4 * cm)

    y -= 8
    y = new_page_if_needed(c, y)
    y = draw_section_box(c, "Top Overdue Cases", x, y, content_width)
    overdue_items = [
        f"{row['case_id']} | {row['queue_status']} | {row['assigned_reviewer']} | overdue {row['overdue_days']} hari | {row['next_action']}"
        for row in overdue_rows[:5]
    ]
    y = draw_bullet_list(c, overdue_items, x + 0.2 * cm, y, content_width - 0.4 * cm)

    y -= 8
    y = new_page_if_needed(c, y)
    y = draw_section_box(c, "Reviewer Workload", x, y, content_width)
    reviewer_items = [
        f"{row['assigned_reviewer']}: {row['total_cases']} kasus"
        for row in reviewer_rows[:5]
    ]
    y = draw_bullet_list(c, reviewer_items, x + 0.2 * cm, y, content_width - 0.4 * cm)

    y -= 8
    y = new_page_if_needed(c, y)
    y = draw_section_box(c, "High Risk Highlights", x, y, content_width)
    if high_risk_rows:
        risk_items = [
            f"{row['case_id']} | {row['participant_name']} | anomaly score {row['anomaly_score']} | overdue {row['overdue_days']} hari"
            for row in high_risk_rows
        ]
        y = draw_bullet_list(c, risk_items, x + 0.2 * cm, y, content_width - 0.4 * cm)
    else:
        y = draw_wrapped_text(c, "Tidak ada high risk overdue cases pada data saat ini.", x + 0.2 * cm, y, content_width - 0.4 * cm)

    y -= 8
    y = new_page_if_needed(c, y)
    y = draw_section_box(c, "Supervisor Notes", x, y, content_width)
    supervisor_notes = [
        "Fokuskan tindak lanjut pada kasus overdue tertinggi dan kasus dengan next action klarifikasi fasilitas.",
        "Monitor reviewer dengan beban kerja tertinggi untuk mengurangi risiko bottleneck.",
        "Gunakan ringkasan ini sebagai brief operasional harian untuk unit review.",
    ]
    y = draw_bullet_list(c, supervisor_notes, x + 0.2 * cm, y, content_width - 0.4 * cm)

    draw_footer(c)
    c.save()

    return (
        f"PDF berhasil dibuat.\n"
        f"Nama file: {filename}\n"
        f"Lokasi file: {file_path}"
    )


if __name__ == "__main__":
    log("Starting PDF MCP server")
    mcp.run()